### ISSUE TITLE
Good idea to allow users to hide their comment posting history, to discourage stalking?

### ISSUE THREAD

**Issue by db0** [DittoToday/Feedback#12]
There's pros and cons to this. Harassed users can use this functionality to prevent people from going through their user history easily and finding "dirt" on them. 

Cons would be that shitposters and trolls would use this to be more difficult to figure out what they do. And stalkers might still be able to do google searches for the same result.

**Comment by michaelfdeberry** [comment]
It sounds like the cons out weight the pros on this one, but I will leave this open.

**Comment by blamm85** [comment]
I think this lies in whether ditto is aiming to be a community where people have reputations and ergo histories or... if we want each conversation to really be independent of anything else and for specific comments to rise/fall by their own merit or lack there of.

**Comment by qaid** [comment]
I've got two questions:

1. How important is Google caching of Ditto's content?
2. Are there no other ways to identify abusive behavior patterns of users?

**Comment by michaelfdeberry** [comment]
@blamm85 I think a plus of having that information available to other users would help them to know if they want to engage the poster or not. Something that I found to happen is that people will bate someone into a conversation just to troll. I think with that information available it's easier to avoid.

@qaid 
1.) Not at all, really. 
2.) That is a good question. I have some ideas for a reputation system, but I am still thinking up parameters of how to make not prone to abuse. 

I am open to suggestions, if you have any ideas.

**Comment by qaid** [comment]
I did a quick Google of "technical troll behavior" 😂 ...

The title of this MIT Technology Review article seems to suggest there's a way to algorithmically identify these types.

_Caveat: I haven't read a word of this beyond the title._

[How a Troll-Spotting Algorithm Learned Its Anti-antisocial Trade](http://www.technologyreview.com/view/536621/how-a-troll-spotting-algorithm-learned-its-anti-antisocial-trade/)

**Comment by db0** [comment]
In regards to the reputation system. You can couple it with something like #19 . Then people can see someone's profile as that person being funny/insightful or whatev. 

To be honest though, you need to think about how you expect people to use comment histories and if the pros (discouraging harassment/stalking) overweight the cons (figuring out trolls). Even if the pros are seemingly lower in number, they may still be more important. It might be that figuring out trolls might not be an issue if the Anti-Oppression policy works as intended.

**Comment by michaelfdeberry** [comment]
@qaid Thanks for the links, I will check them out. 

@db0 Thinking about it more you are right, the user should at least have that choice, and history would really only need to be open to mods and admins. 

The reputations system is probably still a ways off, but I could work the user options in the upcoming updates.

**Comment by db0** [comment]
Follow up suggestion, make the users history hidden, but temporarily revealed to mods when you post in their sub

**Comment by qaid** [comment]
Since problematic comments can be reported, which not rely on trends of those reports highlighting bad community members?

**Comment by michaelfdeberry** [comment]
@db0 @qaid 

Both good points. 

There is a report details page for admins/mods, and it does already list any other reports related to the offending user. 

Putting the user activity on the report page may be the way to go. This should potentially help reduce the likely-hood of abusive mods since they can only see the user activity if the user was reported for something. It should also help against coordinated reporting attacks by allowing the mod to know if the user is problematic or not.  

I still think the feature should be optional, but I will likely make it more granular such as "disable activity stream", "disable comments history", disable submission history", etc.
