### ISSUE TITLE
Initial comment only visible on mouseover

### ISSUE THREAD

**Issue by SabreCat** [DittoToday/Feedback#13]
It appears that when someone shares a link and includes a description, the commentary there only appears in the hover text for the link:

![image](https://cloud.githubusercontent.com/assets/4501321/10950406/2847e4da-82fd-11e5-822b-6aa624d2279c.png)

It'd be valuable for discussion if that description appeared beneath the link and upvote area when you click through to the comments page, or as a comment itself that can be replied to.

**Comment by michaelfdeberry** [comment]
That was by design, with the thought it would mostly be used for a subtitle. Thought I probably should have labeled it subtitle instead of description. 

I can see putting it under the title on the comment page and leaving it as hover text in the listing.
