### ISSUE TITLE
Make submission title editable by the submitter. 

### ISSUE THREAD

**Issue by michaelfdeberry** [DittoToday/Feedback#14]

**Comment by blamm85** [comment]
I don't think this is a good idea. It's one of the few things reddit does right. A title sets the tone for the entire thread. Allowing anyone the power to change it once the conversation is under way can easily misrepresent many a comment and will confuse newcomers to the conversation. 

If anything I'd say only allow the title to be edited if there are no comments yet.

**Comment by michaelfdeberry** [comment]
@blamm85 I agree, but I don't want to stop people from fixing mistakes. 

I think you are on to something though, I might also make it time related too. Then disable it after whichever comes first 2 minutes since posting or the first comment.

**Comment by michaelfdeberry** [comment]
Thinking about this more, I don't think it's worth implementing with all the restrictions. I would imagine the submitter would notice their mistakes soon after posting and would be able to delete and resubmit with a correction.
